# Generated by Django 5.1.3 on 2024-11-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailbatch',
            name='sender_email',
            field=models.EmailField(blank=True, help_text='Email address of the sender', max_length=254, null=True),
        ),
    ]
