# Generated by Django 5.1.3 on 2024-11-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_smsbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbatch',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
